sudo: false
dist: trusty

language: node_js
node_js:
- "8.11.3"

cache:
  directories:
  - node_modules

install:
- npm install
- npm install -g grunt-cli
#- npm install -g codecov

script:
- grunt

#after_success:
#- codecov

before_deploy:
- cp -r . /tmp/grafana-dot-panel-${TRAVIS_TAG}
- cd /tmp
- zip -r grafana-dot-panel-${TRAVIS_TAG}.zip grafana-dot-panel-${TRAVIS_TAG}


deploy:
- provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file: /tmp/grafana-dot-panel-${TRAVIS_TAG}.zip
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
